# FROM python:3.8-slim-buster

FROM python:3.10.11-slim

WORKDIR /app

COPY . /app

# COPY phishfiner .env

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN pip install evidently

CMD [ "python","app.py" ]